apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: ghcr.io/samrudhml/task-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: MONGO_DB
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_SECRET